import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {useEffect} from "react";

const Home: NextPage = () => {
  useEffect(()=> {
      window.open("snssdk3817://webview?biz_id=AWUAABNGzPCzPUiltceOAgo6EAcD&hide_nav_bar=1&url=https://docs.zalopay.vn/", "_blank")
  });

    const handleOpenDeeplink = () => {
        const data ={
            "url":"https://docs.zalopay.vn"
        }

        //@ts-ignore
        ZJSBridge.Device.showToast("Message", e => {console.log(e)})
        // ZJSBridge.Misc.openInAppRw(data, (e: any) => {console.log("demo")})
    }

  return (
    <div className={styles.container}>
      <Head>
        <title>Demo Hello</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          <div className={styles.card}>
            <h2>Click me</h2>
            <button onClick={handleOpenDeeplink}>Open Deeplink</button>
          </div>
        </div>
      </main>
    </div>
  )
}

export default Home
